"""user status and labels side

Revision ID: 0eaa7edee8bd
Revises: ecc75395acfb
Create Date: 2020-11-26 15:52:20.091083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eaa7edee8bd'
down_revision = 'ecc75395acfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('label', sa.Column('side_user_clicked', sa.SmallInteger(), nullable=True))
    op.add_column('label', sa.Column('side_with_lesion', sa.SmallInteger(), nullable=True))
    op.drop_column('label', 'is_correct')
    op.add_column('user', sa.Column('status', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'status')
    op.add_column('label', sa.Column('is_correct', sa.BOOLEAN(), nullable=False))
    op.drop_column('label', 'side_with_lesion')
    op.drop_column('label', 'side_user_clicked')
    # ### end Alembic commands ###
