"""test add active status to batch

Revision ID: 36cbcb26023b
Revises: fd9c6895194a
Create Date: 2020-12-25 23:05:54.773500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36cbcb26023b'
down_revision = 'fd9c6895194a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batch', sa.Column('status', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('batch', 'status')
    # ### end Alembic commands ###
