"""add back in hu

Revision ID: 4437673fda49
Revises: 0eaa7edee8bd
Create Date: 2020-11-26 16:32:10.757518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4437673fda49'
down_revision = '0eaa7edee8bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('hu', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'hu')
    # ### end Alembic commands ###
