"""add instance to labels

Revision ID: 56edcc9a161f
Revises: 4437673fda49
Create Date: 2020-11-27 12:53:41.814633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56edcc9a161f'
down_revision = '4437673fda49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('label', sa.Column('instance', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('label', 'instance')
    # ### end Alembic commands ###
