"""add active status to models

Revision ID: 996a1914dc5f
Revises: 56edcc9a161f
Create Date: 2020-12-25 14:48:42.298721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '996a1914dc5f'
down_revision = '56edcc9a161f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batch', sa.Column('status', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('batch', 'status')
    # ### end Alembic commands ###
