"""add in image and batch table

Revision ID: bcc79ad24637
Revises: 91eba1e780da
Create Date: 2020-11-22 01:53:20.106830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcc79ad24637'
down_revision = '91eba1e780da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('dose_reduction', sa.Numeric(), nullable=True),
    sa.Column('reconstruction', sa.String(length=128), nullable=True),
    sa.Column('attenuation', sa.String(length=128), nullable=True),
    sa.Column('lesion_size_mm', sa.Numeric(), nullable=True),
    sa.Column('size_measurement', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('label', sa.Column('image_id', sa.Integer(), nullable=True))
    op.add_column('label', sa.Column('is_correct', sa.Boolean(), nullable=False))
    op.add_column('label', sa.Column('measurement', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'label', 'image', ['image_id'], ['id'])
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.drop_column('user', 'isAdmin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('isAdmin', sa.BOOLEAN(), nullable=True))
    op.drop_column('user', 'timestamp')
    op.drop_column('user', 'is_admin')
    op.drop_constraint(None, 'label', type_='foreignkey')
    op.drop_column('label', 'measurement')
    op.drop_column('label', 'is_correct')
    op.drop_column('label', 'image_id')
    op.drop_table('image')
    op.drop_table('batch')
    # ### end Alembic commands ###
