"""add filename to image

Revision ID: ecc75395acfb
Revises: c4764caaad8c
Create Date: 2020-11-22 11:43:11.878378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecc75395acfb'
down_revision = 'c4764caaad8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('filename', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'filename')
    # ### end Alembic commands ###
